### ISSUE TITLE
Implement logging in rust-evm

### ISSUE THREAD

**Issue by s-medvedev** [neonlabsorg/neon-evm#10]
It is useful to add logs to the rust-evm implementation to speed up debugging in some cases. However, the logging mechanism is not available there, since this code is used as a library. It is necessary to work out the logging scheme to add debug logs simply. It is worth considering that these logs can be disabled during the build, and this library is also used in two projects (evm-loader, neon-cli) that perform logging in different ways.

┆Issue is synchronized with this [Jira Task](https://neonlabs.atlassian.net/browse/NEON-63) by [Unito](https://www.unito.io)

**Comment by otselnik** [comment]
Researched possible ways of logging realization in rust-evm.
It could be done through next ways:
 - using macroses (like it's done in neon-evm), con of this way is in appearing of unwanted dependencies of solana-sdk in rust-evm
 - using traits - con of this way is in necessity of passing logger variable to every function that could use it
 - using global(static) variable, - con of this way is in using unsafe technics of rust

Choosed the way with least problems - global variable. 
Logger struct with mutable field that affects on way of logging and that could be modified from neon-evm or neon-cli assigned to global variable.
Example implementation :
```
//! EVM logger.
use std::fmt;
use lazy_static::lazy_static;

pub struct Logger {
    ...
}

impl Logger {
    pub fn log(args: fmt::Arguments);
}

lazy_static! {
    static ref EVM_LOGGER: Logger = Logger { ... };
}

#[cfg(not(feature = "no-logs"))]
macro_rules! evm_log {
    ($( $args:expr ),*) => {
        EVM_LOGGER.log(format_args!( $( $args ),* ))
    }
}

#[cfg(feature = "no-logs")]
macro_rules! evm_log {
    ($( $args:expr ),*) => { }
}
```
Usage:
```
use evm_logger::evm_log;
evm_log!("is_succeed {}", 2);
```

**Comment by s-medvedev** [comment]
The BPF has a problem: it does not know how to load programs with a `.bss` section. This section contains all uninitialized global variables. It is necessary to check if the `lazy_static!` variable will be placed in this section.
