### ISSUE TITLE
Running Solidity Contracts

### ISSUE THREAD

**Issue by Zzzzipper** [neonlabsorg/neon-evm#211]
Running various solidity contracts in the Neon EVM engine.

┆Issue is synchronized with this [Jira Task](https://neonlabs.atlassian.net/browse/NEON-161) by [Unito](https://www.unito.io)

**Comment by mich-master** [comment]
pragma solidity ^0.4.25;

contract ZombieFactory {

    event NewZombie(uint zombieId, string name, uint dna);

    uint dnaDigits = 16;
    uint dnaModulus = 10 ** dnaDigits;

    struct Zombie {
        string name;
        uint dna;
    }

    Zombie[] public zombies;

    function _createZombie(string _name, uint _dna) private {
        uint id = zombies.push(Zombie(_name, _dna)) - 1;
        emit NewZombie(id, _name, _dna);
    }

    function _generateRandomDna(string _str) private view returns (uint) {
        uint rand = uint(keccak256(abi.encodePacked(_str)));
        return rand % dnaModulus;
    }

    function createRandomZombie(string _name) public {
        uint randDna = _generateRandomDna(_name);
        _createZombie(_name, randDna);
    }

}

Контракт загружен в Neon EVM, протестированы функции. Ошибок не выявлено.
