### ISSUE TITLE
OpenZeppelin unit test fails. Uncaught Error: The send transactions "from" field must be defined!

### ISSUE THREAD

**Issue by mich-master** [neonlabsorg/neon-evm#246]
**Impact:**
_Proxy + Neon EVM <-> OpenZeppelin library compatibility_

**STR:**

1. Set up Truffle environment for the OpenZeppelin library as described
#219
2. Run the unit test for "AccessControl" contract
`truffle --network solana test ./test/access/AccessControl.test.js`
 

**Actual result:**
Failure message:
Contract: AccessControl
     "after each" hook: after test for "non-admin cannot grant role to other accounts":
     Uncaught Error: The send transactions "from" field must be defined!

**Expected result:**
Test passed successfully.

**Comment by s-medvedev** [comment]
Issue moved to [neonlabsorg/proxy-model.py #278](https://github.com/neonlabsorg/proxy-model.py/issues/278) via [**ZenHub**](https://www.zenhub.com/)
