### ISSUE TITLE
neon-cli deploy doesn't work with `confirmed` commitment

### ISSUE THREAD

**Issue by s-medvedev** [neonlabsorg/neon-evm#27]
**Symptom:** neon-cli fails when try to deploy Ethereum contract with `confirmed` commitment

**STR:**

1. Deploy `evm_loader` and save it address in EVM_LOADER variable
1. Deploy Ethereum contract using

```
neon-cli deploy --evm_loader $EVM_LOADER --commitment confirmed -vvv <contract>
```

**Actual result:**
Fails with error:

```
ERROR - RPC response error -32002: Transaction simulation failed: Blockhash not found
```

**Expected result:**
Successful deployment, awaiting only one confirmation

┆Issue is synchronized with this [Jira Task](https://neonlabs.atlassian.net/browse/NEON-186) by [Unito](https://www.unito.io)

**Comment by otselnik** [comment]
I believe it is fixed in https://github.com/neonlabsorg/neon-evm/pull/47
