### ISSUE TITLE
OpenZeppelin unit test fails. Assertion error: No 'MockFunctionCalled' events found

### ISSUE THREAD

**Issue by mich-master** [neonlabsorg/neon-evm#339]
**Impact:**
_Proxy + Neon EVM  <->  OpenZeppelin library compatibility_

**STR:**
1. Set up Truffle environment for the OpenZeppelin library as described
#219 
2. Run the unit test for "Address" contract
`truffle --network solana test ./test/utils/Address.test.js
`

**Actual result:**
Assertion error:
> Contract: Address
>        functionCall
>          with valid contract receiver
>            calls the requested function:
>       No 'MockFunctionCalled' events found
>       + expected - actual
>       -false
>       +true
> 

**Expected result:**
Test passed successfully.

**Comment by ivandzen** [comment]
Could not reproduce with current version of proxy
