### ISSUE TITLE
Contract selfDestruct function not working

### ISSUE THREAD

**Issue by Chester-King** [neonlabsorg/neon-evm#364]
Contract selfDestruct function not working, EVM throwing error : `Error: Transaction simulation failed: Error processing Instruction 1: instruction changed the balance of a read-only account` 

[Contract code](https://github.com/Chester-King/NeonEVM-Test-Contracts/blob/master/contracts/SelfDestructTest.sol#L16)

[Execution Code](https://github.com/Chester-King/NeonEVM-Test-Contracts/blob/master/migrations/3_selfDestructTest.js#L24)

Reproduction Steps : 

Clone [this repo](https://github.com/Chester-King/NeonEVM-Test-Contracts)
run `npm i`
then make a secrets.json file with mnemonics
run `truffle migrate --network neonDev -f 3 --to 3`

**Comment by mich-master** [comment]
Confirmed. The bug presents at the moment.
