### ISSUE TITLE
Implement precompiled contracts 0x6-0x9 using Solana syscalls

### ISSUE THREAD

**Issue by s-medvedev** [neonlabsorg/neon-evm#453]
┆Issue is synchronized with this [Jira Task](https://neonlabs.atlassian.net/browse/NEON-130) by [Unito](https://www.unito.io)

**Comment by ai-trepalin** [comment]
We need to extract BN256 Pairing inner of loop cycle into the syscall and move rest logic inside EVM Loader Instruction.
