### ISSUE TITLE
Restore tests for precompiled contracts 0x6-0x9

### ISSUE THREAD

**Issue by s-medvedev** [neonlabsorg/neon-evm#454]
┆Issue is synchronized with this [Jira Task](https://neonlabs.atlassian.net/browse/NEON-128) by [Unito](https://www.unito.io)

**Comment by ai-trepalin** [comment]
https://github.com/neonlabsorg/neon-evm/blob/develop/evm_loader/test_solidity_precompiles.py#L331-L361
