### ISSUE TITLE
Computed budget for new alt_bn syscalls

### ISSUE THREAD

**Issue by a-trepalin** [neonlabsorg/neon-evm#459]
We need to compute budget for new syscalls for elliptic curves math: addition, multiplication and pairing.

As a basis, we should get `ecrecover-bench` realization.
https://github.com/neonlabsorg/ecrecover-bench/tree/master/src

Budgets are here: /sdk/src/compute_budget.rs

┆Issue is synchronized with this [Jira Task](https://neonlabs.atlassian.net/browse/NEON-123) by [Unito](https://www.unito.io)

**Comment by ai-trepalin** [comment]
The results are here: https://github.com/neonlabsorg/alt-bn128-bench/blob/main/README.md
