### ISSUE TITLE
Add new operators to testnet/devnet

### ISSUE THREAD

**Issue by vodolaz** [neonlabsorg/neon-evm#467]
1. Name: myz1237
   Solana Pubkey: AqwN5pPsf9pnUZUSo7SmELRrBxxFnycEnTx5spVji4R6
   RPC endpoint: http://65.108.73.124:9090/solana

2. Name: KingSuper
   Solana Pubkey: FtFt7sMNfPUTWKx3otH4aor4KWoFdk9p5qSyxmSj4ZVH
   RPC endpoint: http://142.93.214.90:9090/solana

3. Name: Sergei
   Solana Pubkey: FMMshJoSaNaNFdHseaWAgvHTypS4zggr3fpqEa1FPqYT 
   RPC endpoint: https://51.195.188.28:9090/solana  
   
4. Name: anvel
   Solana pubkey: 2S6YTfDmk3PMZUorMqkCRM8zJqTrMtzu8x5eo1YboMGg
   RPC: http://65.108.64.245:9090/solana

5. Name: maxblock
   Solana pubkey: 72jAG5diJkivWJ2Var2SFuYK2P2vjxaZ2wEUSR23GX7a
   Neon RPC: http://135.125.4.232:9090/solana

6. Name: QuantNode
    Solana pubkey: B5Cwn8y3JaFV622wdkocccJ3U1rfjCWA4S922x2ujLU5
    RPC: http://65.108.101.132:9090/solana 

7. Name: NodesGuru
    Solana Pubkey:  JCjvNTNTfZeo9mSUB4kBVKCJFGiMm4Hux2DSLFubrgVW
    RPC endpoint: http://141.94.137.123:9090/solana

**Comment by mich-master** [comment]
8. Name: P2P
Solana Pubkey: D1apcJxXxAS63cpbTidxjXku7cW2ELQQU9szMQracDSY
