### ISSUE TITLE
Solidity "block.chainid" instruction returns wrong chainId on Devnet

### ISSUE THREAD

**Issue by mich-master** [neonlabsorg/neon-evm#485]
**Impact:**
_Correct work of Solidity "block.chainid" method_

**STR:**
Call the method getChainId() of the contract on Devnet;

```
pragma solidity >=0.5.17;
contract ChainId {  
    function getChainId() public view returns (uint256) {  
        return block.chainid;  
    }  
}  
```

**Actual result:**
111

**Expected result:**
245022926

┆Issue is synchronized with this [Jira Task](https://neonlabs.atlassian.net/browse/NEON-109) by [Unito](https://www.unito.io)

**Comment by ai-trepalin** [comment]
Deploys normally. And it works fine too. But read-only methods are executed on the operator side (inside the emulator). And now it gives out the value of chain_id, which is hard-coded in it (111)

Inside the proxy, there is an eth_call request processing. Here it executes the emulator, which accesses the Solana, takes the actual data of contracts / accounts. And this emulator stores inside itself the chain_id for CI (111). And he must take it from the network with which he works.
