### ISSUE TITLE
Actualize logging format on the facet

### ISSUE THREAD

**Issue by rozhkovdmitrii** [neonlabsorg/neon-evm#496]
## Requirements:

Logging attributes: datetime loglevel pid filename:lineno entity context message
No fixed attribute sizes

**Comment by vakond** [comment]
Format:
```
"%(asctime)s.%(msecs)03d %(levelname)8s %(process)6d:%(threadName)-11s %(name)15s:%(class)-30s %(context)s %(message)s
```

**Comment by rozhkovdmitrii** [comment]
> Format:
> 
> ```
> "%(asctime)s.%(msecs)03d %(levelname)8s %(process)6d:%(threadName)-11s %(name)15s:%(class)-30s %(context)s %(message)s
> ```

```
%(asctime)s.%(msecs)03d %(levelname)-.1s %(filename)s:%(lineno)d %(process)d %(name)s:%(class)s %(context)s %(message)s
```
