### ISSUE TITLE
How do I verify a contract once it is deployed to Neon Evm

### ISSUE THREAD

**Issue by Kaleb47** [neonlabsorg/neon-evm#507]
### Description
Ok so rather than using remix, I decided basic ```Greeter.sol``` contract to neon evm locally though hardhat.

### Contract
```
//SPDX-License-Identifier: Unlicense
pragma solidity ^0.8.0;

import "hardhat/console.sol";

contract Greeter {
    string private greeting;

    constructor(string memory _greeting) {
        console.log("Deploying a Greeter with greeting:", _greeting);
        greeting = _greeting;
    }

    function greet() public view returns (string memory) {
        return greeting;
    }

    function setGreeting(string memory _greeting) public {
        console.log("Changing greeting from '%s' to '%s'", greeting, _greeting);
        greeting = _greeting;
    }
}
```

### Deploy script
    // We require the Hardhat Runtime Environment explicitly here. This is optional
    // but useful for running the script in a standalone fashion through `node <script>`.
    //
    // When running the script with `npx hardhat run <script>` you'll find the Hardhat
    // Runtime Environment's members available in the global scope.
    const hre = require("hardhat");
    
    async function main() {
      // Hardhat always runs the compile task when running scripts with its command
      // line interface.
      //
      // If this script is run directly using `node` you may want to call compile
      // manually to make sure everything is compiled
      // await hre.run('compile');
    
      // We get the contract to deploy
      const Greeter = await hre.ethers.getContractFactory("Greeter");
      const greeter = await Greeter.deploy("Hello, Hardhat!");
    
      await greeter.deployed();
    
      console.log("Greeter deployed to:", greeter.address);
    }
    
    // We recommend this pattern to be able to use async/await everywhere
    // and properly handle errors.
    main()
      .then(() => process.exit(0))
      .catch((error) => {
        console.error(error);
        process.exit(1);
      });### hardhat.config.ts
```
require("@nomiclabs/hardhat-waffle");
let secret = require("./secret")

// This is a sample Hardhat task. To learn how to create your own go to
// https://hardhat.org/guides/create-task.html
task("accounts", "Prints the list of accounts", async (taskArgs, hre) => {
  const accounts = await hre.ethers.getSigners();

  for (const account of accounts) {
    console.log(account.address);
  }
});

// You need to export an object to set up your config
// Go to https://hardhat.org/config/ to learn more

/**
 * @type import('hardhat/config').HardhatUserConfig
 */
module.exports = {
  solidity: "0.8.4",
  networks: {
    NeonEVMDevNet: {
      url: secret.url,
      accounts: [secret.key]
    }
  }
};
```

This file imports a ```secret.json``` file which contains my private key to my metamask wallet and an rpc link connecting the node.
![image](https://user-images.githubusercontent.com/63081938/152270901-a728875f-d925-48e5-b100-19a95332530c.png)

### deployment
My smart contract was successfully compiled so I ran the deploy script.

![image](https://user-images.githubusercontent.com/63081938/152270960-04420858-b491-420d-975c-b17ea6a9e1f7.png)

All I know is the contract was deployed somewhere. I can't verify it on solscan or etherscan. What should I do??

┆Issue is synchronized with this [Jira Task](https://neonlabs.atlassian.net/browse/NEON-59) by [Unito](https://www.unito.io)

**Comment by mich-master** [comment]
Just start using the contract at given address.

**Comment by ihorbond** [comment]
Interested as well. Which block explorer do we use to check this transaction ?

**Comment by mich-master** [comment]
Block explorers for Neon EVM are currently under development.
