### ISSUE TITLE
Smart deploy script for tests

### ISSUE THREAD

**Issue by a-trepalin** [neonlabsorg/neon-evm#539]
This issue is the continuation of https://github.com/neonlabsorg/neon-evm/issues/520

I decided to take it out because the implementation of the issue requires additional research, in contrast to the simple implementation of modes in the original issue.

We can optimize the steps in `deploy-test.sh` so they don't slow things down. Let the script follow them, and not the developer constantly keeps in mind what he needs to do now. As examples:
a. `Wait-for-solana` will run without delay when the Solana is running.
b. Deploy EVM can be made conditional — only if it differs from the one loaded in the chain.

┆Issue is synchronized with this [Jira Task](https://neonlabs.atlassian.net/browse/NEON-53) by [Unito](https://www.unito.io)

**Comment by ai-trepalin** [comment]
As @s-medvedev said:

> All of these options can be removed:
> 1. waiting for solana - if solana is successfully launched, then the waiting should exit immediately (you need to check if this is the case inside the wait-for-solana.sh script)
> 2. updating evm_loader.so - we know the address of the program and can check by checksum whether the version we need is currently loaded into the blockchain or not. This is done quickly enough, and if the version is wrong, then we update it.
> 3. creating test accounts - we can check that all test accounts are created as we expect (and even check the balances at the start!). And skip the account creation step if everything is in order.
> As a result, the developer will not need to think about what situation the blockchain is in at the moment and what options need to be specified. The script will take care of all this work and free the developer for really useful tasks.
