### ISSUE TITLE
Out of Gas problem in Neon transfer transaction

### ISSUE THREAD

**Issue by mich-master** [neonlabsorg/neon-evm#585]
While transferring Neons from an account1 (with Neons on balance) to account2 (without Neons on balance) via Metamask the problem encountered - "Transaction failed".
A brief analysis showed that transaction failed with "Out of Gas" error.

To investigate the problem, filter Logs in Elastic DB on Devnet by
req_id = b431fbf

Additional info:
`$ neon-cli-v0.7.0 -u devnet --evm_loader eeLSJgWzzxrqKv1UxtRVVH8FX3qCQWUs9QuAjJpETGU get-ether-account-data 0xE88FA6b326602d3D9dF8628e122f49bF37E48a0E2022-03-15 10:57:17.767 I account_storage.rs:176 3714331 Emulator:Undefined  Not found account for 0xe88fa6b326602d3d9df8628e122f49bf37e48a0e => CYwyXkACRErLHcoz3D3XeG9Jtk6hZqGN6AGLPm2DWwxQ
2022-03-15 10:57:18.811 T account_storage.rs:179 3714331 Emulator:Undefined  Account found
2022-03-15 10:57:18.811 T account_storage.rs:180 3714331 Emulator:Undefined  Account data len 256
2022-03-15 10:57:18.811 T account_storage.rs:181 3714331 Emulator:Undefined  Account owner eeLSJgWzzxrqKv1UxtRVVH8FX3qCQWUs9QuAjJpETGU
2022-03-15 10:57:18.811 I account_storage.rs:196 3714331 Emulator:Undefined  code_account == None
Ethereum address: 0xe88fa6b326602d3d9df8628e122f49bf37e48a0e
Solana address: CYwyXkACRErLHcoz3D3XeG9Jtk6hZqGN6AGLPm2DWwxQ
Account fields
    address: 0xe88f…8a0e
    bump_seed: 255
    trx_count: 0
    code_account: None
    ro_blocked_count: 0
    rw_blocked: false
    balance: 10000000000000000000`

┆Issue is synchronized with this [Jira Task](https://neonlabs.atlassian.net/browse/NEON-36) by [Unito](https://www.unito.io)

**Comment by gigimon** [comment]
fixed in https://github.com/neonlabsorg/proxy-model.py/pull/634
