### ISSUE TITLE
Parameter for emulator: number of steps to execute

### ISSUE THREAD

**Issue by vakond** [neonlabsorg/neon-evm#705]
Emulator restricts number of steps to execute in a single run. This protects proxy from entering infinite loop in case of gas limit exceeded. Now this parameter is hardcoded as `100_000`.

The parameter should be passed to the command `neon-cli emulate` as non-required option `--max_steps_to_execute` with default value `100_000`.

The parameter should be set in the environment and declared in `environment_data.py` with default value `100_000`. Name of the environment variable should be `MAX_EVM_STEPS_TO_EXECUTE`.

This feature doesn't need a dedicated integration test.

**Comment by rozhkovdmitrii** [comment]
@vakond , please look at `EVM_STEP_COUNT` variable. What the difference between them. The first one is used to check if emulated steps exeuted doesn't exceed the `EVM_STEP_COUNT` * 25. Can we use the only one environment or even rename them to make the difference clear.
